apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: echo-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - animalrescue.online
    secretName: echo-tls
  rules:
  - host: animalrescue.online
    http:
      paths:
      - path: /echo1
        backend:
          serviceName: echo1
          servicePort: 80
      - path: /echo2
        backend:
          serviceName: echo2
          servicePort: 80
