apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: gcloud-dns-issuer-1
  namespace: animal-rescue
spec:
  acme:
    email: ybai@pivotal.io
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        clouddns:
          # The ID of the GCP project
          project: cf-spring-scs
          # This is the secret used to access the service account
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-acct
            key: gcp-key.json
